on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: yarn lint

      - name: Run tests
        run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: "Merge #main -> #gh-pages"
        run: git merge origin/main

      - name: Install dependencies
        run: yarn install

      - name: Build site
        run: yarn build

      - name: Publish changes
        run: |
          git add docs
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff-index --quiet HEAD || git commit -m "docs: update static site"
          git push origin gh-pages